version: '2'
services:
    app:
        build: ""
        container_name: "app_1"
        environment:
            - NODE_ENV=development
            - FOO=bar
        volumes:
            - .:/usr/app:rw
            - /usr/app/node_modules
        ports:
            - 3000:3000
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb_1"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="wmazur"
          - MONGODB_PASS="zaq1@WSX"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
